# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'change_confirmation.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_change_confirmation(object):
    def setupUi(self, change_confirmation):
        change_confirmation.setObjectName("change_confirmation")
        change_confirmation.resize(368, 250)
        self.verticalLayout = QtWidgets.QVBoxLayout(change_confirmation)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.confirmation_label = QtWidgets.QLabel(change_confirmation)
        self.confirmation_label.setMinimumSize(QtCore.QSize(0, 50))
        self.confirmation_label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.confirmation_label.setAlignment(QtCore.Qt.AlignCenter)
        self.confirmation_label.setWordWrap(True)
        self.confirmation_label.setObjectName("confirmation_label")
        self.verticalLayout.addWidget(self.confirmation_label)
        self.widget = QtWidgets.QWidget(change_confirmation)
        self.widget.setMinimumSize(QtCore.QSize(0, 50))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem1)
        self.confirmation_line = QtWidgets.QLineEdit(self.widget)
        self.confirmation_line.setMinimumSize(QtCore.QSize(300, 30))
        self.confirmation_line.setObjectName("confirmation_line")
        self.horizontalLayout.addWidget(self.confirmation_line)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem2)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.timer_label = QtWidgets.QLabel(change_confirmation)
        self.timer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.timer_label.setObjectName("timer_label")
        self.verticalLayout.addWidget(self.timer_label)
        self.widget_4 = QtWidgets.QWidget(change_confirmation)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.code_submit_button = QtWidgets.QPushButton(self.widget_4)
        self.code_submit_button.setCheckable(True)
        self.code_submit_button.setAutoRepeat(True)
        self.code_submit_button.setObjectName("code_submit_button")
        self.horizontalLayout_2.addWidget(self.code_submit_button)
        spacerItem4 = QtWidgets.QSpacerItem(94, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout.addWidget(self.widget_4)
        self.resend_button = QtWidgets.QPushButton(change_confirmation)
        self.resend_button.setCheckable(True)
        self.resend_button.setAutoRepeat(True)
        self.resend_button.setObjectName("resend_button")
        self.verticalLayout.addWidget(self.resend_button)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem5)

        self.retranslateUi(change_confirmation)
        QtCore.QMetaObject.connectSlotsByName(change_confirmation)

    def retranslateUi(self, change_confirmation):
        _translate = QtCore.QCoreApplication.translate
        change_confirmation.setWindowTitle(_translate("change_confirmation", "Form"))
        self.confirmation_label.setText(_translate("change_confirmation", "Please enter the confirmation code sent to your registered email"))
        self.timer_label.setText(_translate("change_confirmation", "TextLabel"))
        self.code_submit_button.setText(_translate("change_confirmation", "submit"))
        self.resend_button.setText(_translate("change_confirmation", "Did not get the code?"))
