# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'disclaimer_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Disclaimer(object):
    def setupUi(self, Disclaimer):
        Disclaimer.setObjectName("Disclaimer")
        Disclaimer.resize(312, 320)
        self.verticalLayout = QtWidgets.QVBoxLayout(Disclaimer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.disclaimer_label = QtWidgets.QLabel(Disclaimer)
        self.disclaimer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.disclaimer_label.setWordWrap(True)
        self.disclaimer_label.setObjectName("disclaimer_label")
        self.verticalLayout.addWidget(self.disclaimer_label)
        self.button_widget_disclaimer = QtWidgets.QWidget(Disclaimer)
        self.button_widget_disclaimer.setObjectName("button_widget_disclaimer")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.button_widget_disclaimer)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.proceed_button = QtWidgets.QPushButton(self.button_widget_disclaimer)
        self.proceed_button.setObjectName("proceed_button")
        self.horizontalLayout.addWidget(self.proceed_button)
        self.cancel_button = QtWidgets.QPushButton(self.button_widget_disclaimer)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.verticalLayout.addWidget(self.button_widget_disclaimer)

        self.retranslateUi(Disclaimer)
        QtCore.QMetaObject.connectSlotsByName(Disclaimer)

    def retranslateUi(self, Disclaimer):
        _translate = QtCore.QCoreApplication.translate
        Disclaimer.setWindowTitle(_translate("Disclaimer", "Form"))
        self.disclaimer_label.setText(_translate("Disclaimer", "Deleting the file will result in the permanent removal of correlated transactions"))
        self.proceed_button.setText(_translate("Disclaimer", "Proceed"))
        self.cancel_button.setText(_translate("Disclaimer", "Cancel"))
