# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'live_output_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_live_output_window(object):
    def setupUi(self, live_output_window):
        live_output_window.setObjectName("live_output_window")
        live_output_window.resize(774, 216)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(live_output_window.sizePolicy().hasHeightForWidth())
        live_output_window.setSizePolicy(sizePolicy)
        live_output_window.setMinimumSize(QtCore.QSize(750, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(live_output_window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(live_output_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMinimumSize(QtCore.QSize(750, 0))
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)

        self.retranslateUi(live_output_window)
        QtCore.QMetaObject.connectSlotsByName(live_output_window)

    def retranslateUi(self, live_output_window):
        _translate = QtCore.QCoreApplication.translate
        live_output_window.setWindowTitle(_translate("live_output_window", "Form"))
